### ISSUE TITLE
Some bugs when I use "PYCHARM" to run 

### ISSUE THREAD

**Issue by tiankonghenlan20113046** [betterenvi/Ullman-Isomorphism#4]
Dear author, 
I am trying to use pycharm to run this code, but it gives me some bugs as following.
```
E:\Users\wzq\Anaconda3\pythonw.exe F:/Code/Ullman-Isomorphism/main.py
Traceback (most recent call last):
  File "F:/Code/Ullman-Isomorphism/main.py", line 4, in <module>
    from UllmanAlgorithm import *
  File "F:\Code\Ullman-Isomorphism\UllmanAlgorithm.py", line 4, in <module>
    from Graph import *
  File "F:\Code\Ullman-Isomorphism\Graph.py", line 46
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Process finished with exit code 1
```
Please how to fix it ?

**Comment by betterenvi** [comment]
Python version
